UI_TEXT = {
    "en": {
        "window_title": "Healthcare Assistant",
        "welcome_message": "👋 Welcome! I'm your AI healthcare assistant. How can I help you today?",
        "health_query_btn": "🩺 General Health",
        "symptom_checker_btn": "🔍 Symptom Checker",
        "language_btn": "🌐 ខ្មែរ",
        "theme_btn": "☀️",
        "input_placeholder": "Type your message here...",
        "send_btn": "Send",
        "mode_label_health": "💬 <b>General Health Information</b>",
        "mode_label_symptom": "🔍 <b>Symptom Checker</b>",
        "switched_to_health": "✅ Switched to General Health mode.",
        "switched_to_symptom": "✅ Switched to Symptom Checker mode.",
        "switched_to_en": "✅ Language changed to English.",
        "switched_to_km": "✅ ប្តូរភាសាទៅខ្មែរ។",
        "you": "You",
        "bot": "Healthcare AI",
        "mock_health_response": "Thank you for your health question! Based on general guidelines, I recommend maintaining a balanced diet, regular exercise, and adequate sleep. For specific concerns, please consult with a qualified healthcare professional.",
        "mock_symptom_response": "I've reviewed your symptoms. This could be related to several common conditions. Consider rest, hydration, and monitor how you feel. If symptoms persist or worsen, please consult a healthcare provider. Note: This is not a medical diagnosis."
    },
    "km": {
        "window_title": "ជំនួយការសុខភាព",
        "welcome_message": "👋 សូមស្វាគមន៍! ខ្ញុំជាជំនួយការ AI សុខភាពរបស់អ្នក។ តើខ្ញុំអាចជួយអ្នកដោយរបៀបណា?",
        "health_query_btn": "🩺 សុខភាពទូទៅ",
        "symptom_checker_btn": "🔍 ពិនិត្យរោគសញ្ញា",
        "language_btn": "🌐 English",
        "theme_btn": "☀️",
        "input_placeholder": "សរសេរសាររបស់អ្នកនៅទីនេះ...",
        "send_btn": "ផ្ញើ",
        "mode_label_health": "💬 <b>ព័ត៌មានសុខភាពទូទៅ</b>",
        "mode_label_symptom": "🔍 <b>ពិនិត្យរោគសញ្ញា</b>",
        "switched_to_health": "✅ បានប្តូរទៅរបៀបសុខភាពទូទៅ។",
        "switched_to_symptom": "✅ បានប្តូរទៅរបៀបពិនិត្យរោគសញ្ញា។",
        "switched_to_en": "✅ Language changed to English.",
        "switched_to_km": "✅ បានប្តូរភាសាទៅខ្មែរ។",
        "you": "អ្នក",
        "bot": "AI សុខភាព",
        "mock_health_response": "សូមអរគុណសម្រាប់សំណួរសុខភាពរបស់អ្នក! ដោយផ្អែកលើគោលការណ៍ណែនាំទូទៅ ខ្ញុំសូមផ្តល់អនុសាសន៍ឱ្យរក្សាអាហារមានតុល្យភាព ធ្វើលំហាត់ប្រាណជាទៀងទាត់ និងការគេងគ្រប់គ្រាន់។ សម្រាប់បញ្ហាជាក់លាក់ សូមពិគ្រោះជាមួយអ្នកជំនាញសុខភាព។",
        "mock_symptom_response": "ខ្ញុំបានពិនិត្យរោគសញ្ញារបស់អ្នក។ នេះអាចទាក់ទងនឹងស្ថានភាពធម្មតាជាច្រើន។ សូមសម្រាក ផឹកទឹកគ្រប់គ្រាន់ និងតាមដានអារម្មណ៍។ ប្រសិនបើរោគសញ្ញានៅតែមាន ឬកាន់តែធ្ងន់ធ្ងរ សូមពិគ្រោះជាមួយគ្រូពេទ្យ។ ចំណាំ៖ នេះមិនមែនជាការធ្វើរោគវិនិច្ឆ័យវេជ្ជសាស្ត្រនោះទេ។"
    }
}
